server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rekcheckdb
    username: postgres
    password: Maulida03.


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    root: INFO
    com.bni.rekcheck: DEBUG
  file:
    name: logs/app-log.json
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}", "level":"%p", "logger":"%c", "message":"%m"}%n'

    # application.yml
management:
  endpoints:
    web:
      exposure:
        include: "*,prometheus"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true


